spring.jpa.hibernate.ddl-auto=validate
spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3307/mydatabase}
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.show-sql=${JPA_SHOW_SQL:false}
spring.flyway.enabled=true
spring.flyway.baseline-on-migrate=${FLYWAY_BASELINE_ON_MIGRATE:false}

logging.level.org.hibernate=${HIBERNATE_LOG_LEVEL:INFO}
logging.level.org.springframework.orm.jpa=${SPRING_JPA_LOG_LEVEL:INFO}
