ALTER TABLE tb_user MODIFY COLUMN username VARCHAR(50) NOT NULL;
ALTER TABLE tb_user MODIFY COLUMN email VARCHAR(255) NOT NULL;
ALTER TABLE tb_user MODIFY COLUMN password VARCHAR(72) NOT NULL;
ALTER TABLE tb_user ADD CONSTRAINT uk_tb_user_email UNIQUE (email);
